### ISSUE TITLE
NuGet package does not expose SpeechletAppAsync

### ISSUE THREAD

**Issue by ElvenMonky** [realares/Ra.AlexaSkillsKit.NET#4]
The Ra.AlexaSkillsKit.csproj file includes SpeechletAsync.cs instead of SpeechletAppAsync.cs and contents of SpeechletAsync.cs are commented out. Thus SpeechletAppAsync is not exposed by resulting library.

**Comment by realares** [comment]
Thank you for your comment. I forgot to publish a new NuGet package. V2.3.0 has just been released.
